apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: python-app
  namespace: argo
spec:
  serviceAccountName: argo
  entrypoint: python-app
  volumes:
  - name: test-volume
    hostPath:
      path: /path/to/tests
  templates:
  - name: python-app
    steps:
    - - name: build
        template: build
    - - name: test
        template: test
    - - name: deploy
        template: deploy
  - name: build
    container:
      image: python:3.11
      command: [python]
      args: ["-c","print('build')"]
  - name: test
    container:
      image: python:3.11
      command: [python]
      args: ["-m","unittest","discover", "-s", "/app/tests"]
      volumeMounts:
      - name: test-volume
        mountPath: /app/tests
  - name: deploy
    container:
      image: python:3.11
      command: [python]
      args: ["-c","print('deploy')"]
